---
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  namespace: kubeflow
  name: random
spec:
  objective:
    type: maximize
    goal: 100
    objectiveMetricName: accuracy
  algorithm:
    algorithmName: random
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  parameters:
    - name: epochs
      parameterType: integer
      feasibleSpace:
        min: "5"
        max: "20"
    - name: l1
      parameterType: double
      feasibleSpace:
        min: "0.0"
        max: "0.5"
    - name: l2
      parameterType: double
      feasibleSpace:
        min: "0.0"
        max: "0.5"
    - name: num_hidden
      parameterType: integer
      feasibleSpace:
        min: "16"
        max: "256"
    - name: learning_rate
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.1"
  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: epochs
        description: Number of training epochs
        reference: epochs
      - name: l1
        description: First output dense layer regularization.. Values range from 0 to 1.
        reference: l1
      - name: l2
        description: Final output dense layer regularization. Values range from 0 to 1.
        reference: l2
      - name: numHidden
        description: Number of hidden units in first output dense layer. 
        reference: num_hidden
      - name: learningRate
        description: Learning rate for the training model
        reference: lr
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          spec:
            containers:
              - name: training-container
                image: docker.io/jacheung6/tutorial-training-container:latest
                command:
                  - "python3"
                  - "/opt/training-pipeline.py"
                  - "--mlflow_experiment_name='test-mnist'"
                  - "--epochs=${trialParameters.epochs}"
                  - "--l1=${trialParameters.l1}"
                  - "--l2=${trialParameters.l2}"
                  - "--num_hidden=${trialParameters.numHidden}"
                  - "--lr=${trialParameters.learningRate}"
                resources:
                  limits:
                    memory: "1Gi"
                    cpu: "0.5"
            restartPolicy: Never